name: Download File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install requests
    - name: Download file
      run: python ./script.py
      env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          
    - name: Commit file
      env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
      run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          
           
          
          
          
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push      
