name: Action Practice

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests
      - name: Run
        run: python3 ./script.py
      - name: Configure Git LFS
    
        run: git lfs install   
      - name: Track all files with Git LFS
        run: |
         echo "* filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
         git lfs track "*"  
      - name: Commit
        env:
         GIT_NAME: GitHub Actions[Bot]
         GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

  
        run: |
          
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git config --global --add safe.directory "*"
          git add .
          git stash

          git remote add origin https://github.com/Map987/images.git
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push -f origin main
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: main
